# Generated by Django 5.2.6 on 2025-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
