# Generated by Django 5.2.4 on 2025-10-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_offercategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercategory',
            name='badge_color',
            field=models.CharField(default='red', help_text="Badge color (e.g., 'red', 'blue', 'green', 'orange')", max_length=50),
        ),
        migrations.AddField(
            model_name='offercategory',
            name='category_label',
            field=models.CharField(blank=True, help_text="Category label shown above title (e.g., 'Electronics', 'Fashion')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Badge text like 'HOT', 'NEW', 'SALE' - shown next to title", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='CSS icon class (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='link',
            field=models.CharField(help_text='URL/Link for this offer category - redirects when clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='name',
            field=models.CharField(help_text="Internal category name (e.g., 'flash-sale', 'clearance')", max_length=100),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='title',
            field=models.CharField(help_text="Display title shown in dropdown (e.g., 'Flash Sale', 'Clearance Items')", max_length=150),
        ),
    ]
