# Generated by Django 5.2.4 on 2025-10-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_offercategory_badge_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offercategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Special Offer', 'verbose_name_plural': 'Special Offers'},
        ),
    ]
