# Generated by Django 5.2.6 on 2025-10-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_minimum_purchase'),
        ('website', '0004_add_offercategory_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offercategory',
            name='category_label',
        ),
        migrations.AddField(
            model_name='offercategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a product category for this offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_offers', to='products.category'),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='link',
            field=models.CharField(help_text="URL/Link for this offer category - redirects when clicked (e.g., 'https://example.com' or '/products')", max_length=500),
        ),
    ]
