# Generated by Django 5.2.4 on 2025-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_is_active_alter_brand_name_and_more'),
        ('website', '0005_change_category_label_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Internal Link'), ('external', 'External Link'), ('dropdown', 'Dropdown Menu')], db_index=True, default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show as featured offer'),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='name',
            field=models.CharField(db_index=True, help_text="Internal category name (e.g., 'flash-sale', 'clearance')", max_length=100),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='title',
            field=models.CharField(db_index=True, help_text="Display title shown in dropdown (e.g., 'Flash Sale', 'Clearance Items')", max_length=150),
        ),
        migrations.AddIndex(
            model_name='navbarsettings',
            index=models.Index(fields=['is_active', 'order'], name='navbar_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='navbarsettings',
            index=models.Index(fields=['parent', 'is_active'], name='navbar_parent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='offercategory',
            index=models.Index(fields=['is_active', 'is_featured', 'order'], name='offer_act_feat_ord_idx'),
        ),
    ]
