# Generated by Django 5.2.4 on 2025-09-23 05:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Featured Products, Most Selling Products', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly section name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this section')),
                ('section_type', models.CharField(choices=[('product', 'Product Based'), ('category', 'Category Based'), ('special_offer', 'Special Offer Based')], help_text='Type of section', max_length=20)),
                ('title_display', models.CharField(blank=True, help_text='Title to display on frontend', max_length=200)),
                ('subtitle_display', models.CharField(blank=True, help_text='Subtitle to display on frontend', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('max_items', models.PositiveIntegerField(default=10, help_text='Maximum number of items to display in this section', validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for special offers', max_digits=5, null=True)),
                ('offer_start_date', models.DateTimeField(blank=True, null=True)),
                ('offer_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_name', models.CharField(choices=[('home', 'Home Page'), ('cart', 'Cart Page'), ('categories', 'Categories Page'), ('checkout', 'Checkout Page'), ('products', 'Products Page'), ('product_detail', 'Product Detail Page'), ('shop', 'Shop Page'), ('search', 'Search Results Page')], max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show this section on this page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of section on this page')),
                ('items_per_row', models.PositiveIntegerField(default=4, help_text='Number of items to show per row on this page', validators=[django.core.validators.MinValueValidator(1)])),
                ('show_title', models.BooleanField(default=True, help_text='Show section title on this page')),
                ('show_subtitle', models.BooleanField(default=True, help_text='Show section subtitle on this page')),
                ('show_view_all', models.BooleanField(default=True, help_text="Show 'View All' button")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_assignments', to='sections.section')),
            ],
            options={
                'verbose_name': 'Page Section Assignment',
                'verbose_name_plural': 'Page Section Assignments',
                'ordering': ['page_name', 'order'],
                'unique_together': {('section', 'page_name')},
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the section')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured item in section')),
                ('custom_title', models.CharField(blank=True, help_text='Custom title for this item in section', max_length=200)),
                ('custom_description', models.TextField(blank=True, help_text='Custom description for this item in section')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special price for this item in this section', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sections.section')),
            ],
            options={
                'verbose_name': 'Section Item',
                'verbose_name_plural': 'Section Items',
                'ordering': ['order', 'created_at'],
                'unique_together': {('section', 'category'), ('section', 'product')},
            },
        ),
    ]
