# Generated by Django 5.2.4 on 2025-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_is_active_alter_brand_name_and_more'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this section on this page'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order of section on this page'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home Page'), ('cart', 'Cart Page'), ('categories', 'Categories Page'), ('checkout', 'Checkout Page'), ('products', 'Products Page'), ('product_detail', 'Product Detail Page'), ('shop', 'Shop Page'), ('search', 'Search Results Page')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(db_index=True, help_text='e.g., Featured Products, Most Selling Products', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='offer_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='offer_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('product', 'Product Based'), ('category', 'Category Based'), ('special_offer', 'Special Offer Based')], db_index=True, help_text='Type of section', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as featured item in section'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order within the section'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['page_name', 'is_active', 'order'], name='page_sec_pg_act_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active', 'order'], name='section_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_type', 'is_active'], name='section_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['section', 'order'], name='sec_item_sec_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['section', 'is_featured'], name='sec_item_sec_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['product', 'section'], name='sec_item_prod_sec_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['category', 'section'], name='sec_item_cat_sec_idx'),
        ),
    ]
