# Generated by Django 5.2.4 on 2025-10-24 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_product_minimum_purchase'),
        ('users', '0003_wholesalerprofile_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Electronics, Fragile Items, Heavy Items', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what types of products belong to this category')),
            ],
            options={
                'verbose_name': 'Shipping Category',
                'verbose_name_plural': 'Shipping Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., By Air, By Ship, Door to Door', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price (used if no tiers defined)', max_digits=10)),
                ('delivery_estimated_time', models.CharField(blank=True, help_text="e.g., '1-2 days', '5-7 days', '2-3 weeks'", max_length=50, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight this shipping method can handle (in kg). Leave blank for no weight limit.', max_digits=10, null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity this shipping method can handle. Leave blank for no quantity limit.', null=True)),
                ('preferred_pricing_type', models.CharField(choices=[('quantity', 'Quantity-based'), ('weight', 'Weight-based')], default='quantity', help_text='Preferred pricing method for this shipping method', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cart_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before shipping and discounts', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number for order tracking', max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='Required customer name', max_length=100)),
                ('customer_email', models.EmailField(db_index=True, help_text='Required customer email', max_length=254)),
                ('customer_phone', models.CharField(help_text='Required customer phone number', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shipping_address', models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ForeignKey(blank=True, help_text='Shipping method', null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.shippingmethod')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_account_number', models.CharField(help_text='Required backend-set account number', max_length=50)),
                ('sender_number', models.CharField(help_text="Required customer's payment number", max_length=50)),
                ('transaction_id', models.CharField(help_text='Required transaction/Reference ID', max_length=100)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text="e.g., 'Package has left the warehouse.'", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FreeShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=2, help_text='Minimum order amount required for free shipping', max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Shipping categories this rule applies to. Leave blank for all categories.', to='orders.shippingcategory')),
            ],
            options={
                'verbose_name': 'Free Shipping Rule',
                'verbose_name_plural': 'Free Shipping Rules',
                'ordering': ['-threshold_amount'],
            },
        ),
        migrations.AddField(
            model_name='shippingcategory',
            name='allowed_shipping_methods',
            field=models.ManyToManyField(blank=True, help_text='Shipping methods available for this category', related_name='shipping_categories', to='orders.shippingmethod'),
        ),
        migrations.CreateModel(
            name='ShippingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Minimum quantity required for this pricing tier (for quantity-based pricing)', null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this pricing tier (leave empty for unlimited)', null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight in kg required for this pricing tier (for weight-based pricing)', max_digits=8, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in kg for this pricing tier (leave empty for unlimited)', max_digits=8, null=True)),
                ('pricing_type', models.CharField(choices=[('quantity', 'Quantity-based'), ('weight', 'Weight-based')], default='quantity', help_text='Whether this tier is based on quantity or weight', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this tier', max_digits=10)),
                ('has_incremental_pricing', models.BooleanField(default=False, help_text='Enable incremental pricing for weights/quantities above the minimum')),
                ('increment_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Additional cost per unit (kg for weight, item for quantity) above minimum', max_digits=10, null=True)),
                ('increment_unit_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Size of each increment unit (e.g., 0.5 for every 0.5kg, 1.0 for every 1kg)', max_digits=8)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority tiers will be selected first when multiple tiers match')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tiers', to='orders.shippingmethod')),
            ],
            options={
                'verbose_name': 'Shipping Tier',
                'verbose_name_plural': 'Shipping Tiers',
                'ordering': ['pricing_type', 'priority', 'min_quantity', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('MIN_PRODUCT_QUANTITY', 'Minimum Product Quantity'), ('SHIPPING_DISCOUNT', 'Shipping Discount'), ('CART_TOTAL_DISCOUNT', 'Cart Total Discount'), ('FIRST_TIME_USER', 'First Time User'), ('USER_SPECIFIC', 'User Specific')], db_index=True, default='PRODUCT_DISCOUNT', max_length=25)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5)),
                ('min_quantity_required', models.PositiveIntegerField(default=1, help_text='Minimum quantity required to apply coupon')),
                ('min_cart_total', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required for CART_TOTAL_DISCOUNT', max_digits=10, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Coupon becomes valid from this date and time')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Coupon expiration date and time')),
                ('eligible_users', models.ManyToManyField(blank=True, help_text='Users eligible for USER_SPECIFIC coupons', related_name='specific_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'active'], name='coupon_code_active_idx'), models.Index(fields=['active', 'expires_at'], name='coupon_active_expires_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'product'], name='orderitem_order_product_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-ordered_at'], name='order_ordered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-ordered_at'], name='order_user_ordered_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-ordered_at'], name='order_status_ordered_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email', '-ordered_at'], name='order_email_ordered_idx'),
        ),
    ]
