# Generated by Django 5.2.4 on 2025-11-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('COD_PENDING', 'Cash on Delivery - Pending')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='admin_account_number',
            field=models.CharField(blank=True, help_text='Required backend-set account number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('cod', 'Cash on Delivery')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='sender_number',
            field=models.CharField(blank=True, help_text="Required customer's payment number", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Required transaction/Reference ID', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CashOnDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(help_text='Full name for delivery verification', max_length=100)),
                ('alternative_phone', models.CharField(help_text='Alternative contact number for delivery coordination', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Special delivery instructions from customer', null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered & Paid'), ('PAYMENT_FAILED', 'Payment Failed at Delivery'), ('RETURNED', 'Returned to Sender')], default='PENDING', help_text='Current delivery status for COD order', max_length=20)),
                ('delivery_attempts', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts made')),
                ('delivery_notes', models.TextField(blank=True, help_text='Internal delivery notes for delivery team', null=True)),
                ('amount_to_collect', models.DecimalField(decimal_places=2, help_text='Total amount to collect from customer at delivery', max_digits=12)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount collected at delivery', max_digits=12)),
                ('payment_collected_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was collected', null=True)),
                ('delivery_person_name', models.CharField(blank=True, help_text='Name of delivery person', max_length=100, null=True)),
                ('delivery_person_phone', models.CharField(blank=True, help_text='Delivery person contact number', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_delivery_date', models.DateField(blank=True, help_text='Scheduled delivery date', null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Actual delivery timestamp', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_on_delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'Cash on Delivery',
                'verbose_name_plural': 'Cash on Delivery Orders',
                'indexes': [models.Index(fields=['delivery_status', '-created_at'], name='cod_status_created_idx'), models.Index(fields=['scheduled_delivery_date'], name='cod_scheduled_date_idx')],
            },
        ),
    ]
