# Generated by Django 5.2.4 on 2025-11-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpayment_payment_method'),
        ('users', '0004_alter_address_is_default_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Delivery address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='users.address'),
        ),
    ]
