# Generated by Django 5.2.4 on 2025-12-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_address_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='admin_account_number',
            field=models.CharField(blank=True, help_text="Admin's account number for receiving payment", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='sender_number',
            field=models.CharField(blank=True, help_text="Customer's payment number", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction/Reference ID', max_length=100, null=True),
        ),
    ]
