# Generated by Django 5.2.6 on 2025-10-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage for affiliates (e.g., 5.00 for 5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price for wholesale orders (leave empty if not applicable)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CategoryMinimumOrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(help_text='Minimum quantity required for wholesale orders in this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='Category for which minimum order quantity applies', on_delete=django.db.models.deletion.CASCADE, related_name='minimum_order_quantity', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Minimum Order Quantity',
                'verbose_name_plural': 'Category Minimum Order Quantities',
                'ordering': ['category__name'],
            },
        ),
    ]
