# Generated by Django 5.2.4 on 2025-10-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_affiliate_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_purchase',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required for wholesale orders. Admin can set different values per product (e.g., Mobile=10, Laptop=5, Fashion=60)'),
        ),
    ]
