# Generated by Django 5.2.4 on 2025-12-01 17:28

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_is_active_alter_brand_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_landing_page',
            field=models.BooleanField(default=False, help_text='Enable dedicated landing page for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='landing_features',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Product features to display on landing page', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='landing_how_to_use',
            field=ckeditor.fields.RichTextField(blank=True, help_text='How to use instructions for landing page', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='landing_why_choose',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Why should customers choose this product', null=True),
        ),
        migrations.CreateModel(
            name='LandingPageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at the time of order', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (unit_price * quantity)', max_digits=10)),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(db_index=True, help_text="Customer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('detailed_address', models.TextField(help_text='Complete delivery address')),
                ('is_wholesaler', models.BooleanField(default=False, help_text='Whether this is a wholesale order')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Additional notes from customer', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landing_orders', to='products.product')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page Order',
                'verbose_name_plural': 'Landing Page Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='landing_order_created_idx'), models.Index(fields=['status', '-created_at'], name='landing_order_status_idx'), models.Index(fields=['product', '-created_at'], name='landing_order_product_idx'), models.Index(fields=['email', '-created_at'], name='landing_order_email_idx')],
            },
        ),
    ]
