# Generated by Django 5.2.4 on 2025-12-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_enable_landing_page_product_landing_features_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMinimumOrderQuantity',
        ),
    ]
