# Generated by Django 5.2.4 on 2026-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_variantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_facebook_pixel',
            field=models.BooleanField(db_index=True, default=False, help_text='Enable Facebook Pixel tracking for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='facebook_pixel_access_token',
            field=models.CharField(blank=True, help_text='Facebook Pixel Access Token (kept secure, not exposed via API)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, db_index=True, help_text='Product-specific Facebook Pixel ID', max_length=100, null=True),
        ),
    ]
