# Generated by Django 5.2.4 on 2026-01-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_variant_orderitem_orderitem_variant_idx'),
        ('products', '0010_product_enable_facebook_pixel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageorder',
            name='alternative_phone',
            field=models.CharField(blank=True, help_text='Alternative contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpageorder',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping charge based on selected method', max_digits=10),
        ),
        migrations.AddField(
            model_name='landingpageorder',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Selected shipping method', null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.shippingmethod'),
        ),
    ]
