# Generated by Django 5.2.4 on 2026-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_landingpageorder_alternative_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price (unit_price * quantity + shipping)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='landingpageorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price at the time of order', max_digits=10),
        ),
    ]
