# Generated by Django 5.2.4 on 2026-01-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_landingpageorder_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageorder',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected product variant if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_orders', to='products.productvariant'),
        ),
    ]
