# Generated by Django 5.2.4 on 2026-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_landingpageorder_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total available quantity. Set to 0 for preorder-only'),
        ),
    ]
