# Generated by Django 5.2.4 on 2026-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Total available quantity. Set to 0 for preorder-only'),
        ),
    ]
