# Generated by Django 5.2.4 on 2025-10-24 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contact_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is the shop currently open for business?'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Has the shop been verified by the admin?'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active', 'is_verified'], name='shop_active_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active', '-created_at'], name='shop_active_created_idx'),
        ),
    ]
