# Generated by Django 5.2.6 on 2025-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type_affiliateprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalerprofile',
            name='business_type',
            field=models.CharField(blank=True, help_text='Type of business (e.g., Import/Export, Retail, Manufacturing)', max_length=100, null=True),
        ),
    ]
